language: node_js
dist: trusty
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_d97a72ff12e3_key -iv $encrypted_d97a72ff12e3_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "a298003154"
- git config --global user.email "298003154@qq.com"
install:
- npm install
script:
- hexo clean
- hexo g
after_success:
- hexo deploy
